[package]
name = "JOB-RECOMMENATION-SYSTEM"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1.6"
actix-web = "4.3.0"
ndarray-linalg = "0.16.0"
ndarray = "0.15.4"
ndarray-stats = "0.5.1"
serde = { version = "1.0.130", features = ["derive"] }
rust-nlp = "0.1.0"